version: '3.8'

services:

  postgres:
    build: postgres
    env_file: .env
    volumes:
      - ../.mega-game/postgres:/var/lib/postgresql/data
    restart: always

  mega-game:
    build: .
    env_file: .env
    depends_on:
      - postgres
    command: npm start
    ports:
      - "8080:8080"
    restart: always
